#!/bin/sh

# The path of the collection
COLLECTION=$1

# The path of the default directory
cwd=$(pwd)

# do the indexing job using ATIRE
cd $COLLECTION/data
$cwd/atire/bin/index -N10000 -findex $cwd/index.aspt -rrtrec:tag:nitf:doc-id 1987 1988 1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 2007


# now convert the index into a JASS index
cd $(cwd)
JASSv2/JASSv1/atire_to_jass_index index.aspt -G 
